/*
   VaaniBank AI — Card Service Form Configuration
   Union Bank of India | Team Vectora
   */

// Card Service Field Labels
export const CARD_FIELD_LABELS = {
  // 1. Basic Details
  customer_id: {
    en: "Customer ID",
    hi: "ग्राहक आईडी",
    mr: "ग्राहक आयडी",
    ta: "வாடிக்கையாளர் ஐடி",
    te: "కస్టమర్ ఐడి",
    bn: "গ্রাহক আইডি",
    kn: "ಗ್ರಾಹಕ ಐಡಿ",
    gu: "ગ્રાહક આઈડી",
    pa: "ਗਾਹಕ ਆਈਡੀ",
    or: "ଗ୍ରାହକ ଆଇଡି",
    ml: "കസ്റ്റമർ ഐഡി",
  },
  account_no: {
    en: "Account Number",
    hi: "खाता संख्या",
    mr: "खाते क्रमांक",
    ta: "கணக்கு எண்",
    te: "ఖాతా సంఖ్య",
    bn: "অ্যাকাউন্ট নম্বর",
    kn: "ಖಾತೆ ಸಂಖ್ಯೆ",
    gu: "ખાતા નંબર",
    pa: "ਖਾਤਾ ਨੰਬਰ",
    or: "ଖାତା ନମ୍ବର",
    ml: "അക്കൗണ്ട് നമ്പർ",
  },
  first_name: {
    en: "First Name",
    hi: "पहला नाम",
    mr: "पहिले नाव",
    ta: "முதல் பெயர்",
    te: "మొదటి పేరు",
    bn: "প্রথম নাম",
    kn: "ಮೊದಲ ಹೆಸರು",
    gu: "પ્રથમ નામ",
    pa: "ਪਹਿਲਾ ਨਾਮ",
    or: "ପ୍ରଥମ ନାମ",
    ml: "ആദ്യനാമം",
  },
  middle_name: {
    en: "Middle Name",
    hi: "मध्य नाम",
    mr: "मधले नाव",
    ta: "நடுப் பெயர்",
    te: "మధ్య పేరు",
    bn: "মাঝের নাম",
    kn: "ಮಧ್ಯದ ಹೆಸರು",
    gu: "મધ્યમ નામ",
    pa: "ਵਿਚਕਾਰਲਾ ਨਾਮ",
    or: "ମଝି ନାମ",
    ml: "മധ്യനാമം",
  },
  last_name: {
    en: "Last Name",
    hi: "अंतिम नाम",
    mr: "आडनाव",
    ta: "கடைசி பெயர்",
    te: "చివరి పేరు",
    bn: "পদবি",
    kn: "ಕೊನೆಯ ಹೆಸರು",
    gu: "અટક",
    pa: "ਆਖਰੀ ਨਾਮ",
    or: "ଶେଷ ନାମ",
    ml: "അവസാനനാമം",
  },
  mobile_no: {
    en: "Mobile Number",
    hi: "मोबाइल नंबर",
    mr: "मोबाईल नंबर",
    ta: "மொபைல் எண்",
    te: "మొబైల్ సంఖ్య",
    bn: "মোবাইল নম্বর",
    kn: "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    gu: "મોબાઇલ નંબર",
    pa: "ਮੋਬਾਈਲ ਨੰਬਰ",
    or: "ମୋବାଇଲ୍ ନମ୍ବର",
    ml: "മൊബൈൽ നമ്പർ",
  },
  email_id: {
    en: "Email ID",
    hi: "ईमेल आईडी",
    mr: "ईमेल आयडी",
    ta: "மின்னஞ்சல் ஐடி",
    te: "ఈమెయిల్ ఐడి",
    bn: "ইমেল আইডি",
    kn: "ಇಮೇಲ್ ಐಡಿ",
    gu: "ઈમેલ આઈડી",
    pa: "ਈਮੇਲ ਆਈਡੀ",
    or: "ଇମେଲ୍ ଆଇଡି",
    ml: "ഇമെയിൽ ഐഡി",
  },
  dob: {
    en: "Date of Birth",
    hi: "जन्म तिथि",
    mr: "जन्म तारीख",
    ta: "பிறந்த தேதி",
    te: "పుట్టిన తేదీ",
    bn: "জন্ম তারিখ",
    kn: "ಹುಟ್ಟಿದ ದಿನಾಂಕ",
    gu: "જન્મ તારીખ",
    pa: "ਜਨਮ ਮਿਤੀ",
    or: "ଜନ୍ମ ତାରିଖ",
    ml: "ജനന തീയതി",
  },
  pan_no: {
    en: "PAN Number",
    hi: "पैन नंबर",
    mr: "पॅन नंबर",
    ta: "பான் எண்",
    te: "పాన్ సంఖ్య",
    bn: "প্যান নম্বর",
    kn: "ಪ್ಯಾನ್ ಸಂಖ್ಯೆ",
    gu: "પાન નંબર",
    pa: "ਪੈਨ ਨੰਬਰ",
    or: "ପ୍ୟାନ୍ ନମ୍ବର",
    ml: "പാൻ നമ്പർ",
  },
  aadhaar_no: {
    en: "Aadhaar Number",
    hi: "आधार नंबर",
    mr: "आधार नंबर",
    ta: "ஆதார் எண்",
    te: "ఆధార్ సంఖ్య",
    bn: "আধার নম্বর",
    kn: "ಆಧಾರ್ ಸಂಖ್ಯೆ",
    gu: "આધાર નંબર",
    pa: "ਆਧਾਰ ਨੰਬਰ",
    or: "ଆଧାର ନମ୍ବର",
    ml: "ആധാർ നമ്പർ",
  },

  // 2. Address Details
  address_type: {
    en: "Address Type",
    hi: "पते का प्रकार",
    mr: "पत्त्याचा प्रकार",
    ta: "முகவரி வகை",
    te: "చిరునామా రకం",
    bn: "ঠিকানার ধরন",
    kn: "ವಿಳಾಸದ ಪ್ರಕಾರ",
    gu: "સરનામાંનો પ્રકાર",
    pa: "ਪਤੇ ਦੀ ਕਿਸਮ",
    or: "ଠିକଣା ପ୍ରକାର",
    ml: "വിലാസ തരം",
  },
  city: {
    en: "City",
    hi: "शहर",
    mr: "शहर",
    ta: "நகரம்",
    te: "నగరం",
    bn: "শহর",
    kn: "ನಗರ",
    gu: "શહેર",
    pa: "ਸ਼ਹਿਰ",
    or: "ସହର",
    ml: "നഗരം",
  },
  pin: {
    en: "PIN Code",
    hi: "पिन कोड",
    mr: "पिन कोड",
    ta: "பின் கோடு",
    te: "పిన్ కోడ్",
    bn: "পিন কোড",
    kn: "ಪಿನ್ ಕೋಡ್",
    gu: "પિન કોડ",
    pa: "ਪਿੰਨ ਕੋਡ",
    or: "ପିନ୍ କୋଡ୍",
    ml: "പിൻ കോഡ്",
  },
  state: {
    en: "State",
    hi: "राज्य",
    mr: "राज्य",
    ta: "மாநிலம்",
    te: "రాష్ట్రం",
    bn: "রাজ্য",
    kn: "ರಾಜ್ಯ",
    gu: "રાજ્ય",
    pa: "ਰਾਜ",
    or: "ରାଜ୍ୟ",
    ml: "സംസ്ഥാനം",
  },

  // 3. Card Service Selection
  card_service_type: {
    en: "Card Service Required",
    hi: "आवश्यक कार्ड सेवा",
    mr: "आवश्यक कार्ड सेवा",
    ta: "தேவையான கார்டு சேவை",
    te: "అవసరమైన కార్డ్ సేవ",
    bn: "প্রয়োজনীয় কার্ড পরিষেবা",
    kn: "ಕಾರ್ಡ್ ಸೇವೆ ಅಗತ್ಯವಿದೆ",
    gu: "જરૂરી કાર્ડ સેવા",
    pa: "ਕਾਰਡ ਸੇਵਾ ਦੀ ਲੋੜ ਹੈ",
    or: "ଆବଶ୍ୟକ କାର୍ଡ ସେବା",
    ml: "ആവശ്യമായ കാർഡ് സേവനം",
  },
  old_card_no: {
    en: "Old Card Number (If any)",
    hi: "पुराना कार्ड नंबर (यदि कोई हो)",
    mr: "जुना कार्ड नंबर (असल्यास)",
    ta: "பழைய கார்டு எண் (ஏதேனும் இருந்தால்)",
    te: "పాత కార్డ్ నంబర్ (ఏదైనా ఉంటే)",
    bn: "পুরানো কার্ড নম্বর (যদি থাকে)",
    kn: "ಹಳೆಯ ಕಾರ್ಡ್ ಸಂಖ್ಯೆ (ಇದ್ದರೆ)",
    gu: "જૂનો કાર્ડ નંબર (જો હોય તો)",
    pa: "ਪੁਰਾਣਾ ਕਾਰਡ ਨੰਬਰ (ਜੇ ਕੋਈ ਹੋਵੇ)",
    or: "ପୁରୁଣା କାର୍ଡ ନମ୍ବର (ଯଦି କିଛି ଥାଏ)",
    ml: "പഴയ കാർഡ് നമ്പർ (ഉണ്ടെങ്കിൽ)",
  },

  // 4. Dedicated Card Preferences
  name_on_card: {
    en: "Name on Card (Max 20 chars)",
    hi: "कार्ड पर नाम",
    mr: "कार्डवरील नाव",
    ta: "கார்டில் உள்ள பெயர்",
    te: "కార్డ్‌పై పేరు",
    bn: "কার্ডে নাম",
    kn: "ಕಾರ್ಡ್‌ನಲ್ಲಿರುವ ಹೆಸರು",
    gu: "કાર્ડ પરનું નામ",
    pa: "ਕਾਰਡ 'ਤੇ ਨਾਮ",
    or: "କାର୍ଡରେ ନାମ",
    ml: "കാർഡിലെ പേര്",
  },
  card_network: {
    en: "Card Network",
    hi: "कार्ड नेटवर्क",
    mr: "कार्ड नेटवर्क",
    ta: "கார்டு நெட்வொர்க்",
    te: "కార్డ్ నెట్‌వర్క్",
    bn: "কার্ড নেটওয়ার্ক",
    kn: "ಕಾರ್ಡ್ ನೆಟ್‌ವರ್ಕ್",
    gu: "કાર્ડ નેટવર્ક",
    pa: "ਕਾਰਡ ਨੈੱਟਵਰਕ",
    or: "କାର୍ଡ ନେଟୱାର୍କ",
    ml: "കാർഡ് നെറ്റ്‌വർക്ക്",
  },
  delivery_preference: {
    en: "Delivery Preference",
    hi: "वितरण प्राथमिकता",
    mr: "वितरण पसंती",
    ta: "டெலிவரி விருப்பம்",
    te: "డెలివరీ ప్రాధాన్యత",
    bn: "ডেলিভারি পছন্দ",
    kn: "ವಿತರಣಾ ಆದ್ಯತೆ",
    gu: "ડિલિવરી પસંદગી",
    pa: "ਡਿਲੀਵਰੀ ਦੀ ਤਰਜੀਹ",
    or: "ବିତରଣ ପସନ୍ଦ",
    ml: "ഡെലിവറി മുൻഗണന",
  },
  atm_preference: {
    en: "ATM Usage Preference",
    hi: "ATM उपयोग प्राथमिकता",
    mr: "ATM वापर पसंती",
    ta: "ஏடிஎம் பயன்பாட்டு விருப்பம்",
    te: "ATM వినియోగ ప్రాధాన్యత",
    bn: "এটিএম ব্যবহারের পছন্দ",
    kn: "ಎಟಿಎಂ ಬಳಕೆಯ ಆದ್ಯತೆ",
    gu: "એટીએમ વપરાશ પસંદગી",
    pa: "ਏਟੀਐਮ ਵਰਤੋਂ ਦੀ ਤਰਜੀਹ",
    or: "ATM ବ୍ୟବହାର ପସନ୍ଦ",
    ml: "എടിഎം ഉപയോഗ മുൻഗണന",
  },
  pos_preference: {
    en: "POS/E-comm Preference",
    hi: "POS/ई-कॉम प्राथमिकता",
    mr: "POS/ई-कॉम पसंती",
    ta: "பிஓஎஸ்/இ-காம் விருப்பம்",
    te: "POS/E-comm ప్రాధాన్యత",
    bn: "পিওএস/ই-কম পছন্দ",
    kn: "ಪಿಒಎಸ್/ಇ-ಕಾಮ್ ಆದ್ಯತೆ",
    gu: "પીઓએસ/ઈ-કોમ પસંદગી",
    pa: "ਪੀਓਐਸ/ਈ-ਕਾਮ ਤਰਜੀਹ",
    or: "POS/E-comm ପସନ୍ଦ",
    ml: "പിഒഎസ്/ഇ-കോം മുൻഗണന",
  },
  mobile_banking_reg: {
    en: "Register for Union ease App",
    hi: "यूनियन ईज़ ऐप के लिए पंजीकरण करें",
    mr: "यूनियन ईझ ॲपसाठी नोंदणी करा",
    ta: "யூனியன் ஈஸ் ஆப்-க்கு பதிவு செய்யவும்",
    te: "యూనియన్ ఈజ్ యాప్ కోసం నమోదు చేసుకోండి",
    bn: "ইউনিয়ন ইজ অ্যাপের জন্য নিবন্ধন করুন",
    kn: "ಯೂನಿಯನ್ ಈಸ್ ಆಪ್‌ಗಾಗಿ ನೋಂದಾಯಿಸಿ",
    gu: "યુનિયન ઇઝ એપ માટે નોંધણી કરો",
    pa: "ਯੂਨੀਅਨ ਈਜ਼ ਐਪ ਲਈ ਰਜਿਸਟਰ ਕਰੋ",
    or: "ୟୁନିଅନ୍ ଇଜ୍ ଆପ୍ ପାଇଁ ପଞ୍ଜିକରଣ କରନ୍ତୁ",
    ml: "യൂണിയൻ ഈസ് ആപ്പിനായി രജിസ്റ്റർ ചെയ്യുക",
  },
};

// Card Service Field Options
export const CARD_FIELD_OPTIONS = {
  address_type: [
    { value: "communication", label: { en: "Communication", hi: "पत्राचार" } },
    { value: "permanent", label: { en: "Permanent", hi: "स्थायी" } },
    { value: "office", label: { en: "Office", hi: "कार्यालय" } },
  ],
  card_service_type: [
    { value: "ready_kit", label: { en: "Ready Kit Debit Card", hi: "रेडी किट डेबिट कार्ड" } },
    { value: "personalised_primary", label: { en: "Personalised Primary Card", hi: "व्यक्तिगत प्राथमिक कार्ड" } },
    { value: "personalised_addon", label: { en: "Personalised Add-on Card", hi: "व्यक्तिगत एड-ऑन कार्ड" } },
    { value: "duplicate_card", label: { en: "Duplicate ATM/Debit Card", hi: "डुप्लिकेट एटीएम/डेबिट कार्ड" } },
  ],
  card_network: [
    { value: "rupay", label: { en: "RuPay", hi: "रूपे" } },
    { value: "visa", label: { en: "VISA", hi: "वीज़ा" } },
    { value: "mastercard", label: { en: "Mastercard", hi: "मास्टरकार्ड" } },
  ],
  delivery_preference: [
    { value: "mailing_address", label: { en: "Mailing Address", hi: "पत्राचार का पता" } },
    { value: "branch_address", label: { en: "Branch Address", hi: "शाखा का पता" } },
  ],
  atm_preference: [
    { value: "domestic", label: { en: "Domestic Only", hi: "केवल घरेलू" } },
    { value: "international", label: { en: "International Only", hi: "केवल अंतरराष्ट्रीय" } },
    { value: "both", label: { en: "Both", hi: "दोनों" } },
    { value: "none", label: { en: "None", hi: "कोई नहीं" } },
  ],
  pos_preference: [
    { value: "domestic", label: { en: "Domestic Only", hi: "केवल घरेलू" } },
    { value: "international", label: { en: "International Only", hi: "केवल अंतरराष्ट्रीय" } },
    { value: "both", label: { en: "Both", hi: "दोनों" } },
    { value: "none", label: { en: "None", hi: "कोई नहीं" } },
  ],
};

// Card Service Field Groups
export const CARD_INTENT_FIELDS = [
  // Basic Details
  "customer_id",
  "account_no",
  "first_name",
  "middle_name",
  "last_name",
  "mobile_no",
  "email_id",
  "dob",
  "pan_no",
  "aadhaar_no",

  // Address
  "address_type",
  "city",
  "pin",
  "state",

  // Service Selection
  "card_service_type",
  "old_card_no",

  // Preferences
  "name_on_card",
  "card_network",
  "delivery_preference",
  "atm_preference",
  "pos_preference",
  "mobile_banking_reg",
];

export const CARD_SELECT_FIELDS = [
  "address_type",
  "card_service_type",
  "card_network",
  "delivery_preference",
  "atm_preference",
  "pos_preference",
];

export const CARD_CHECKBOX_FIELDS = [
  "mobile_banking_reg",
];

export const CARD_FIELD_STATUS = {
  mandatory: ["customer_id", "account_no", "first_name", "last_name", "mobile_no", "card_service_type"],
  conditional: ["old_card_no", "name_on_card", "card_network"],
  optional: ["middle_name", "email_id", "mobile_banking_reg"],
};
