/*
   VaaniBank AI — Loan Form Configuration
   Union Bank of India | Team Vectora
   */

// Loan Field Labels (11 Languages)
export const LOAN_FIELD_LABELS = {
  // 1. Core: Common Retail Loan Application
  customer_name: {
    en: "Full Name",
    hi: "पूरा नाम",
    mr: "पूर्ण नाव",
    ta: "முழு பெயர்",
    te: "పూర్తి పేరు",
    bn: "পুরো নাম",
    kn: "ಪೂರ್ಣ ಹೆಸರು",
    gu: "પૂરું નામ",
    pa: "ਪੂਰਾ ਨਾਮ",
    or: "ପୁରା ନାମ",
    ml: "പൂർണ്ണനാമം",
  },
  dob: {
    en: "Date of Birth",
    hi: "जन्म तिथि",
    mr: "जन्म तारीख",
    ta: "பிறந்த தேதி",
    te: "పుట్టిన తేదీ",
    bn: "জন্ম তারিখ",
    kn: "ಹುಟ್ಟಿದ ದಿನಾಂಕ",
    gu: "જન્મ તારીખ",
    pa: "ਜਨਮ ਮਿਤੀ",
    or: "ଜନ୍ମ ତାରିଖ",
    ml: "ജനന തീയതി",
  },
  pan_no: {
    en: "PAN Number",
    hi: "पैन नंबर",
    mr: "पॅन नंबर",
    ta: "பான் எண்",
    te: "పాన్ సంఖ్య",
    bn: "প্যান নম্বর",
    kn: "ಪ್ಯಾನ್ ಸಂಖ್ಯೆ",
    gu: "પાન નંબર",
    pa: "ਪੈਨ ਨੰਬਰ",
    or: "ପ୍ୟାନ୍ ନମ୍ବର",
    ml: "പാൻ നമ്പർ",
  },
  aadhaar_no: {
    en: "Aadhaar Number",
    hi: "आधार नंबर",
    mr: "आधार नंबर",
    ta: "ஆதார் எண்",
    te: "ఆధార్ సంఖ్య",
    bn: "আধার নম্বর",
    kn: "ಆಧಾರ್ ಸಂಖ್ಯೆ",
    gu: "આધાર નંબર",
    pa: "ਆਧਾਰ ਨੰਬਰ",
    or: "ଆଧାର ନମ୍ବର",
    ml: "ആധാർ നമ്പർ",
  },
  occupation_type: {
    en: "Occupation Type",
    hi: "व्यवसाय का प्रकार",
    mr: "व्यवसायाचा प्रकार",
    ta: "தொழில் வகை",
    te: "వృత్తి రకం",
    bn: "পেশার ধরণ",
    kn: "ಉದ್ಯೋಗದ ಪ್ರಕಾರ",
    gu: "વ્યવસાયનો પ્રકાર",
    pa: "ਕਿੱਤੇ ਦੀ ਕਿਸਮ",
    or: "ବୃତ୍ତି ପ୍ରକାର",
    ml: "തൊഴിൽ തരം",
  },
  work_experience: {
    en: "Total Work Experience",
    hi: "कुल कार्य अनुभव",
    mr: "एकूण कामाचा अनुभव",
    ta: "மொத்த பணி அனுபவம்",
    te: "మొత్తం పని అనుభవం",
    bn: "মোট কাজের অভিজ্ঞতা",
    kn: "ಒಟ್ಟು ಕೆಲಸದ ಅನುಭವ",
    gu: "કુલ કાર્ય અનુભવ",
    pa: "ਕੁੱਲ ਕੰਮ ਦਾ ਤਜਰਬਾ",
    or: "ମୋଟ କାର୍ଯ୍ୟ ଅଭିଜ୍ଞତା",
    ml: "ആകെ പ്രവൃത്തിപരിചയം",
  },
  net_salary: {
    en: "Net Monthly Salary",
    hi: "शुद्ध मासिक वेतन",
    mr: "निव्वळ मासिक पगार",
    ta: "நிகர மாத சம்பளம்",
    te: "నికర నెలవారీ జీతం",
    bn: "নিট মাসিক বেতন",
    kn: "ನಿವ್ವಳ ಮಾಸಿಕ ವೇತನ",
    gu: "ચોખ્ખો માસિક પગાર",
    pa: "ਸ਼ੁੱਧ ਮਹੀਨਾਵਾਰ ਤਨਖਾਹ",
    or: "ନିଟ୍ ମାସିକ ଦରମା",
    ml: "അറ്റ പ്രതിമാസ ശമ്പളം",
  },
  monthly_obligations: {
    en: "Existing Monthly Obligations",
    hi: "मौजूदा मासिक दायित्व",
    mr: "विद्यमान मासिक जबाबदाऱ्या",
    ta: "தற்போதுள்ள மாத கடமைகள்",
    te: "ప్రస్తుత నెలవారీ బాధ్యతలు",
    bn: "বিদ্যমান মাসিক বাধ্যবাধকতা",
    kn: "ಅಸ್ತಿತ್ವದಲ್ಲಿರುವ ಮಾಸಿಕ ಜವಾಬ್ದಾರಿಗಳು",
    gu: "હાલની માસિક જવાબદારીઓ",
    pa: "ਮੌਜੂਦਾ ਮਹੀਨਾਵਾਰ ਜ਼ਿੰਮੇਵਾਰੀਆਂ",
    or: "ବର୍ତ୍ତମାନର ମାସିକ ଦାୟିତ୍ୱ",
    ml: "നിലവിലുള്ള പ്രതിമാസ ബാധ്യതകൾ",
  },

  // 2. Education Loan Annexure
  academic_record: {
    en: "Previous Academic Record (%)",
    hi: "पिछला शैक्षणिक रिकॉर्ड (%)",
    mr: "मागील शैक्षणिक रेकॉर्ड (%)",
    ta: "முந்தைய கல்வி சாதனை (%)",
    te: "మునుపటి విద్యా రికార్డు (%)",
    bn: "পূর্ববর্তী শিক্ষাগত রেকর্ড (%)",
    kn: "ಹಿಂದಿನ ಶೈಕ್ಷಣಿಕ ದಾಖಲೆ (%)",
    gu: "પાછલો શૈક્ષણિક રેકોર્ડ (%)",
    pa: "ਪਿਛਲਾ ਵਿਦਿਅਕ ਰਿਕਾਰਡ (%)",
    or: "ପୂର୍ବ ଶିକ୍ଷାଗତ ରେକର୍ଡ (%)",
    ml: "മുമ്പത്തെ അക്കാദമിക് റെക്കോർഡ് (%)",
  },
  course_name: {
    en: "Proposed Course Name",
    hi: "प्रस्तावित पाठ्यक्रम का नाम",
    mr: "प्रस्तावित कोर्सचे नाव",
    ta: "முன்மொழியப்பட்ட படிப்பின் பெயர்",
    te: "ప్రతిపాదిత కోర్సు పేరు",
    bn: "প্রস্তাবিত কোর্সের নাম",
    kn: "ಪ್ರಸ್ತಾವಿತ ಕೋರ್ಸ್ ಹೆಸರು",
    gu: "પ્રસ્તાવિત કોર્સનું નામ",
    pa: "ਪ੍ਰਸਤਾਵਿਤ ਕੋਰਸ ਦਾ ਨਾਮ",
    or: "ପ୍ରସ୍ତାବିତ ପାଠ୍ୟକ୍ରମ ନାମ",
    ml: "നിർദ്ദിഷ്ട കോഴ്സിന്റെ പേര്",
  },
  university_name: {
    en: "College/University Name",
    hi: "कॉलेज/विश्वविद्यालय का नाम",
    mr: "कॉलेज/विद्यापीठाचे नाव",
    ta: "கல்லூரி/பல்கலைக்கழகப் பெயர்",
    te: "కళాశాల/విశ్వవిద్యాలయ పేరు",
    bn: "কলেজ/বিশ্ববিদ্যালয়ের নাম",
    kn: "ಕಾಲೇಜು/ವಿಶ್ವವಿದ್ಯಾಲಯದ ಹೆಸರು",
    gu: "કોલેજ/યુનિવર્સિટીનું નામ",
    pa: "ਕਾਲਜ/ਯੂਨੀਵਰਸਿਟੀ ਦਾ ਨਾਮ",
    or: "କଲେଜ/ବିଶ୍ୱବିଦ୍ୟାଳୟ ନାମ",
    ml: "കോളേജ്/യൂണിവേഴ്സിറ്റി പേര്",
  },
  estimated_expenditure: {
    en: "Estimated Total Expenditure",
    hi: "अनुमानित कुल व्यय",
    mr: "अंदाजित एकूण खर्च",
    ta: "மதிப்பிடப்பட்ட மொத்த செலவு",
    te: "అంచనా వేసిన మొత్తం ఖర్చు",
    bn: "আনুমানিক মোট ব্যয়",
    kn: "ಅಂದಾಜು ಒಟ್ಟು ವೆಚ್ಚ",
    gu: "અંદાજિત કુલ ખર્ચ",
    pa: "ਅੰਦਾਜ਼ਨ ਕੁੱਲ ਖਰਚ",
    or: "ଆନୁମାନିକ ମୋଟ ବ୍ୟୟ",
    ml: "കണക്കാക്കിയ ആകെ ചെലവ്",
  },
  margin_money: {
    en: "Margin Money (Self Contribution)",
    hi: "मार्जिन मनी (स्वयं का योगदान)",
    mr: "मार्जिन मनी (स्वतःचे योगदान)",
    ta: "மார்ஜின் பணம் (சுய பங்களிப்பு)",
    te: "మార్జిన్ మనీ (స్వయం సహకారం)",
    bn: "মার্জিন মানি (নিজস্ব অবদান)",
    kn: "ಮಾರ್ಜಿನ್ ಮನಿ (ಸ್ವಂತ ಕೊಡುಗೆ)",
    gu: "માર્જિન મની (સ્વ-યોગદાન)",
    pa: "ਮਾਰਜਿਨ ਮਨੀ (ਸਵੈ ਯੋਗਦਾਨ)",
    or: "ମାର୍ଜିନ୍ ମନି (ସ୍ୱୟଂ ଅବଦାନ)",
    ml: "മാർജിൻ മണി (സ്വന്തം സംഭാവന)",
  },

  // 3. Home Loan Annexure
  property_address: {
    en: "Property Address",
    hi: "संपत्ति का पता",
    mr: "मालमत्तेचा पत्ता",
    ta: "சொத்து முகவரி",
    te: "ఆస్తి చిరునామా",
    bn: "সম্পত্তির ঠিকানা",
    kn: "ಆಸ್ತಿಯ ವಿಳಾಸ",
    gu: "મિલકતનું સરનામું",
    pa: "ਜਾਇਦਾਦ ਦਾ ਪਤਾ",
    or: "ସମ୍ପତ୍ତି ଠିକଣା",
    ml: "വസ്തുവിന്റെ വിലാസം",
  },
  property_type: {
    en: "Property Type (Flat/House/Plot)",
    hi: "संपत्ति का प्रकार",
    mr: "मालमत्तेचा प्रकार",
    ta: "சொத்து வகை",
    te: "ఆస్తి రకం",
    bn: "সম্পত্তির ধরণ",
    kn: "ಆಸ್ತಿಯ ಪ್ರಕಾರ",
    gu: "મિલકતનો પ્રકાર",
    pa: "ਜਾਇਦਾਦ ਦੀ ਕਿਸਮ",
    or: "ସମ୍ପତ୍ତି ପ୍ରକାର",
    ml: "വസ്തുവിന്റെ തരം",
  },
  purchase_price: {
    en: "Property Purchase Price",
    hi: "संपत्ति खरीद मूल्य",
    mr: "मालमत्ता खरेदी किंमत",
    ta: "சொத்து கொள்முதல் விலை",
    te: "ఆస్తి కొనుగోలు ధర",
    bn: "সম্পত্তি ক্রয়ের মূল্য",
    kn: "ಆಸ್ತಿ ಖರೀದಿ ಬೆಲೆ",
    gu: "મિલકત ખરીદ કિંમત",
    pa: "ਜਾਇਦਾਦ ਖਰੀਦ ਮੁੱਲ",
    or: "ସମ୍ପତ୍ତି କ୍ରୟ ମୂଲ୍ୟ",
    ml: "വസ്തു വാങ്ങൽ വില",
  },
  builder_name: {
    en: "Builder/Seller Name",
    hi: "बिल्डर/विक्रेता का नाम",
    mr: "बिल्डर/विक्रेत्याचे नाव",
    ta: "கட்டுமானாளர்/விற்பனையாளர் பெயர்",
    te: "బిల్డర్/విక్రేత పేరు",
    bn: "বিল্ডার/বিক্রেতার নাম",
    kn: "ಬಿಲ್ಡರ್/ಮಾರಾಟಗಾರರ ಹೆಸರು",
    gu: "બિલ્ડર/વેચનારનું નામ",
    pa: "ਬਿਲਡਰ/ਵਿਕਰੇਤਾ ਦਾ ਨਾਮ",
    or: "ବିଲଡର୍/ବିକ୍ରେତା ନାମ",
    ml: "ബിൽഡർ/വിൽപ്പനക്കാരന്റെ പേര്",
  },

  // 4. Vehicle & Personal Loan Annexures
  vehicle_model: {
    en: "Vehicle Make & Model",
    hi: "वाहन का मेक और मॉडल",
    mr: "वाहनाचा मेक आणि मॉडेल",
    ta: "வாகன தயாரிப்பு மற்றும் மாடல்",
    te: "వాహనం మేక్ & మోడల్",
    bn: "যানবাহনের মেক এবং মডেল",
    kn: "ವಾಹನದ ಮಾದರಿ",
    gu: "વાહન મેક અને મોડેલ",
    pa: "ਵਾਹਨ ਦਾ ਮੇਕ ਅਤੇ ਮਾਡਲ",
    or: "ଯାନବାହନ ମେକ୍ ଏବଂ ମଡେଲ୍",
    ml: "വാഹനത്തിന്റെ മേക്ക് & മോഡൽ",
  },
  loan_purpose: {
    en: "Specific Purpose of Loan",
    hi: "ऋण का विशिष्ट उद्देश्य",
    mr: "कर्जाचा विशिष्ट उद्देश",
    ta: "கடனின் குறிப்பிட்ட நோக்கம்",
    te: "రుణం యొక్క నిర్దిష్ట ఉద్దేశ్యం",
    bn: "ঋণের সুনির্দিষ্ট উদ্দেশ্য",
    kn: "ಸಾಲದ ನಿರ್ದಿಷ್ಟ ಉದ್ದೇಶ",
    gu: "લોનનો ચોક્કસ હેતુ",
    pa: "ਕਰਜ਼ੇ ਦਾ ਖਾਸ ਉਦੇਸ਼",
    or: "ଋଣର ନିର୍ଦ୍ଦିଷ୍ଟ ଉଦ୍ଦେଶ୍ୟ",
    ml: "വായ്പയുടെ പ്രത്യേക ലക്ഷ്യം",
  },

  // Shared / General
  loan_type: {
    en: "Loan Type",
    hi: "ऋण का प्रकार",
    mr: "कर्जाचा प्रकार",
    ta: "கடன் வகை",
    te: "రుణ రకం",
    bn: "ঋণের ধরণ",
    kn: "ಸಾಲದ ಪ್ರಕಾರ",
    gu: "લોનનો પ્રકાર",
    pa: "ਕਰਜ਼ੇ ਦੀ ਕਿਸਮ",
    or: "ଋଣ ପ୍ରକାର",
    ml: "വായ്പ തരം",
  },
  form_date: {
    en: "Date",
    hi: "दिनांक",
    mr: "दिनांक",
    ta: "தேதி",
    te: "తేదీ",
    bn: "তারিখ",
    kn: "ದಿನಾಂಕ",
    gu: "તારીખ",
    pa: "ਮਿਤੀ",
    or: "ତାରିଖ",
    ml: "തീയതി",
  },
  place: {
    en: "Place",
    hi: "स्थान",
    mr: "ठिकाण",
    ta: "இடம்",
    te: "స్థలం",
    bn: "স্থান",
    kn: "ಸ್ಥಳ",
    gu: "સ્થળ",
    pa: "ਥਾਂ",
    or: "ସ୍ଥାନ",
    ml: "സ്ഥലം",
  },
};

// Loan Field Options
export const LOAN_FIELD_OPTIONS = {
  loan_type: [
    {
      value: "home_loan",
      label: {
        en: "Home Loan",
        hi: "होम लोन",
        mr: "होम लोन",
        ta: "வீட்டுக் கடன்",
        te: "హోమ్ లోన్",
        bn: "হোম লোন",
        kn: "ಮನೆ ಸಾಲ",
        gu: "હોમ લોન",
        pa: "ਹੋਮ ਲੋਨ",
        or: "ଗୃହ ଋଣ",
        ml: "ഭവന വായ്പ",
      },
    },
    {
      value: "education_loan",
      label: {
        en: "Education Loan",
        hi: "शिक्षा ऋण",
        mr: "शिक्षण कर्ज",
        ta: "கல்விக் கடன்",
        te: "విద్యా రుణం",
        bn: "শিক্ষা ঋণ",
        kn: "ಶಿಕ್ಷಣ ಸಾಲ",
        gu: "શિક્ષણ લોન",
        pa: "ਸਿੱਖਿਆ ਕਰਜ਼ਾ",
        or: "ଶିକ୍ଷା ଋଣ",
        ml: "വിദ്യാഭ്യാസ വായ്പ",
      },
    },
    {
      value: "vehicle_loan",
      label: {
        en: "Vehicle Loan",
        hi: "वाहन ऋण",
        mr: "वाहन कर्ज",
        ta: "வாகனக் கடன்",
        te: "వాహన రుణం",
        bn: "যানবাহন ঋণ",
        kn: "ವಾಹನ ಸಾಲ",
        gu: "વાહન લોન",
        pa: "ਵਾਹਨ ਕਰਜ਼ਾ",
        or: "ଯାନବାହନ ଋଣ",
        ml: "വാഹന വായ്പ",
      },
    },
    {
      value: "personal_loan",
      label: {
        en: "Personal Loan",
        hi: "व्यक्तिगत ऋण",
        mr: "वैयक्तिक कर्ज",
        ta: "தனிநபர் கடன்",
        te: "వ్యక్తిగత రుణం",
        bn: "ব্যক্তিগত ঋণ",
        kn: "ವೈಯಕ್ತಿಕ ಸಾಲ",
        gu: "વ્યક્તિગત લોન",
        pa: "ਨਿੱਜੀ ਕਰਜ਼ਾ",
        or: "ବ୍ୟକ୍ତିଗତ ଋଣ",
        ml: "വ്യക്തിഗത വായ്പ",
      },
    },
  ],
  occupation_type: [
    {
      value: "salaried",
      label: {
        en: "Salaried",
        hi: "वेतनभोगी",
        mr: "पगारदार",
        ta: "சம்பளம் பெறுபவர்",
        te: "జీతగాడు",
        bn: "বেতনভোগী",
        kn: "ವೇತನದಾರರು",
        gu: "પગારદાર",
        pa: "ਤਨਖਾਹਦਾਰ",
        or: "ଦରମା ପ୍ରାପ୍ତ",
        ml: "ശമ്പളമുള്ളവർ",
      },
    },
    {
      value: "self_employed",
      label: {
        en: "Self Employed",
        hi: "स्वरोजगार",
        mr: "स्वयंरोजगार",
        ta: "சுயதொழில்",
        te: "స్వయం ఉపాధి",
        bn: "স্বনির্ভর",
        kn: "ಸ್ವಯಂ ಉದ್ಯೋಗಿ",
        gu: "સ્વ-રોજગાર",
        pa: "ਸਵੈ-ਰੁਜ਼ਗਾਰ",
        or: "ସ୍ୱୟଂ ନିଯୁକ୍ତ",
        ml: "സ്വയം തൊഴിൽ",
      },
    },
    {
      value: "agriculturist",
      label: {
        en: "Agriculturist",
        hi: "कृषक",
        mr: "शेतकरी",
        ta: "விவசாயி",
        te: "వ్యవసాయదారుడు",
        bn: "কৃষিজীবী",
        kn: "ಕೃಷಿಕ",
        gu: "ખેડૂત",
        pa: "ਖੇਤੀਬਾੜੀ ਕਰਨ ਵਾਲਾ",
        or: "କୃଷକ",
        ml: "കർഷകൻ",
      },
    },
    {
      value: "pensioner",
      label: {
        en: "Pensioner",
        hi: "पेंशनभोगी",
        mr: "पेन्शनर",
        ta: "ஓய்வூதியதாரர்",
        te: "పెన్షనర్",
        bn: "পেনশনভোগী",
        kn: "ಪಿಂಚಣಿದಾರರು",
        gu: "પેન્શનર",
        pa: "ਪੈਨਸ਼ਨਰ",
        or: "ପେନସନଧାରୀ",
        ml: "പെൻഷനർ",
      },
    },
  ],
};

// Loan Field Groups
export const LOAN_INTENT_FIELDS = [
  // Core
  "loan_type",
  "customer_name",
  "dob",
  "pan_no",
  "aadhaar_no",
  "occupation_type",
  "work_experience",
  "net_salary",
  "monthly_obligations",

  // Education Loan Annexure (shown only if loan_type is education_loan)
  "academic_record",
  "course_name",
  "university_name",
  "estimated_expenditure",
  "margin_money",

  // Home Loan Annexure (shown only if loan_type is home_loan)
  "property_address",
  "property_type",
  "purchase_price",
  "builder_name",

  // Vehicle / Personal Annexure
  "vehicle_model",
  "loan_purpose",

  // Verification
  "place",
  "form_date",
];

export const LOAN_SELECT_FIELDS = ["loan_type", "occupation_type"];

export const LOAN_CHECKBOX_FIELDS = [
  // Add any boolean flags if needed
];

// Field Requirement Status (Dots)
export const LOAN_FIELD_STATUS = {
  mandatory: [
    "loan_type",
    "customer_name",
    "dob",
    "pan_no",
    "aadhaar_no",
    "occupation_type",
    "net_salary",
    "form_date",
  ],
  conditional: [
    "academic_record",
    "course_name",
    "university_name",
    "estimated_expenditure",
    "property_address",
    "purchase_price",
    "vehicle_model",
    "loan_purpose",
  ],
  optional: [
    "work_experience",
    "monthly_obligations",
    "margin_money",
    "property_type",
    "builder_name",
    "place",
  ],
};
